name: Testing

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/testing.yml'
  pull_request:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/testing.yml'
  schedule:
    # run tests on every week Monday
    - cron: '0 0 * * 1'

jobs:
  testing:
    name: PHP ${{ matrix.php }}, WordPress ${{ matrix.wordpress }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: [ '8.2', '8.1', '8.0', '7.4', '7.3', '7.2' ]
        wordpress: [ '6.1', '6.0', '5.9', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0' ]
        exclude:
          - { php: '7.4', wordpress: '5.0' }
          - { php: '7.4', wordpress: '5.1' }
          - { php: '7.4', wordpress: '5.2' }
          - { php: '8.0', wordpress: '5.0' }
          - { php: '8.0', wordpress: '5.1' }
          - { php: '8.0', wordpress: '5.2' }
          - { php: '8.0', wordpress: '5.3' }
          - { php: '8.0', wordpress: '5.4' }
          - { php: '8.0', wordpress: '5.5' }
          - { php: '8.0', wordpress: '5.6' }
          - { php: '8.0', wordpress: '5.7' }
          - { php: '8.0', wordpress: '5.8' }
          - { php: '8.1', wordpress: '5.0' }
          - { php: '8.1', wordpress: '5.1' }
          - { php: '8.1', wordpress: '5.2' }
          - { php: '8.1', wordpress: '5.3' }
          - { php: '8.1', wordpress: '5.4' }
          - { php: '8.1', wordpress: '5.5' }
          - { php: '8.1', wordpress: '5.6' }
          - { php: '8.1', wordpress: '5.7' }
          - { php: '8.1', wordpress: '5.8' }
          - { php: '8.2', wordpress: '5.0' }
          - { php: '8.2', wordpress: '5.1' }
          - { php: '8.2', wordpress: '5.2' }
          - { php: '8.2', wordpress: '5.3' }
          - { php: '8.2', wordpress: '5.4' }
          - { php: '8.2', wordpress: '5.5' }
          - { php: '8.2', wordpress: '5.6' }
          - { php: '8.2', wordpress: '5.7' }
          - { php: '8.2', wordpress: '5.8' }

    services:
      mysql:
        image: mariadb:10.9.2
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Get composer cache directory
        run: echo "COMPOSER_DIR=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_DIR }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.wordpress }}-${{ matrix.phpunit }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Set PHPUnit for WordPress 5.0
        if: ${{ matrix.wordpress <= '5.0' }}
        run: composer require phpunit/phpunit:~6.5 --dev --no-update

      - name: Set PHPUnit for WordPress 5.1 ~ 5.8
        if: ${{ matrix.wordpress >= '5.1' && matrix.wordpress <= '5.8' }}
        run: composer require phpunit/phpunit:~7.5 --dev --no-update

      - name: Set PHPUnit for WordPress 5.9 ~ 6.1
        if: ${{ matrix.wordpress >= '5.9' && matrix.php <= '7.2' }}
        run: composer require phpunit/phpunit:~8.5 --dev --no-update

      - name: Set PHPUnit for WordPress 5.9 ~ 6.1
        if: ${{ matrix.wordpress >= '5.9' && matrix.php >= '7.3' }}
        run: composer require phpunit/phpunit:~9.5 --dev --no-update

      - name: Install dependencies
        run: composer update --no-progress --no-interaction

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run Composer Validate
        run: composer validate --strict

      - name: Run Composer Normalize
        run: composer normalize --dry-run

      - name: Run coding style checker
        run: ./vendor/bin/phpcs -v --standard=WordPress -- *.php

      - name: Install WP Tests
        run: bash ./bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 ${{ matrix.wordpress }}

      - name: phpunit tests
        run: ./vendor/bin/phpunit
