name: Testing

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/testing.yml'
  pull_request:
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/testing.yml'

jobs:
  testing:
    name: PHP ${{ matrix.php }}, Wordpress ${{ matrix.wordpress }}, DB ${{ matrix.db }}, PHPUnit ${{ matrix.phpunit }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: [ '8.1', '8.0', '7.4', '7.3', '7.2' ]
        wordpress: [ '6.0', '5.9', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0' ]
        db: [ 'mariadb:10.9.2' ]
        exclude:
          - { php: '7.4', wordpress: '5.0' }
          - { php: '7.4', wordpress: '5.1' }
          - { php: '7.4', wordpress: '5.2' }
          - { php: '8.0', wordpress: '5.0' }
          - { php: '8.0', wordpress: '5.1' }
          - { php: '8.0', wordpress: '5.2' }
          - { php: '8.0', wordpress: '5.3' }
          - { php: '8.0', wordpress: '5.4' }
          - { php: '8.0', wordpress: '5.5' }
          - { php: '8.0', wordpress: '5.6' }
          - { php: '8.0', wordpress: '5.7' }
          - { php: '8.0', wordpress: '5.8' }
          - { php: '8.1', wordpress: '5.0' }
          - { php: '8.1', wordpress: '5.1' }
          - { php: '8.1', wordpress: '5.2' }
          - { php: '8.1', wordpress: '5.3' }
          - { php: '8.1', wordpress: '5.4' }
          - { php: '8.1', wordpress: '5.5' }
          - { php: '8.1', wordpress: '5.6' }
          - { php: '8.1', wordpress: '5.7' }
          - { php: '8.1', wordpress: '5.8' }
        include:
          - { php: '7.2', wordpress: '6.0', phpunit: '8.5.30' }
          - { php: '7.3', wordpress: '6.0', phpunit: '9.5.20' }
          - { php: '7.4', wordpress: '6.0', phpunit: '9.5.20' }
          - { php: '8.0', wordpress: '6.0', phpunit: '9.5.20' }
          - { php: '8.1', wordpress: '6.0', phpunit: '9.5.20' }
          - { php: '7.2', wordpress: '5.9', phpunit: '8.5.30' }
          - { php: '7.3', wordpress: '5.9', phpunit: '9.5.20' }
          - { php: '7.4', wordpress: '5.9', phpunit: '9.5.20' }
          - { php: '8.0', wordpress: '5.9', phpunit: '9.5.20' }
          - { php: '8.1', wordpress: '5.9', phpunit: '9.5.20' }
          - { wordpress: '5.8', phpunit: '7.5.20' }
          - { wordpress: '5.7', phpunit: '7.5.20' }
          - { wordpress: '5.6', phpunit: '7.5.20' }
          - { wordpress: '5.5', phpunit: '7.5.20' }
          - { wordpress: '5.4', phpunit: '7.5.20' }
          - { wordpress: '5.3', phpunit: '7.5.20' }
          - { wordpress: '5.2', phpunit: '7.5.20' }
          - { wordpress: '5.1', phpunit: '7.5.20' }
          - { wordpress: '5.0', phpunit: '6.5.14' }

    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP, Tools and Extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Set ergebnis/composer-normalize:~2.19.0 to PHP 7.3 and older versions
        if: ${{ '7.3' >= matrix.php }}
        run: composer require ergebnis/composer-normalize:~2.19.0 --dev --no-interaction --no-progress --no-update

      - name: Set PHPUnit to specific version
        run: composer require phpunit/phpunit:~${{ matrix.phpunit }} --dev --no-interaction --no-progress --no-update

      - name: Install dependencies
        run: composer update --with-all-dependencies --no-interaction --no-progress

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run Composer Validate
        run: composer validate --strict

      - name: Run Composer Normalize
        run: composer normalize --dry-run

      - name: Run coding style checker
        run: ./vendor/bin/phpcs -v --standard=WordPress -- *.php

      - name: Install WP Tests
        run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 ${{ matrix.wordpress }}

      - name: phpunit tests
        run: ./vendor/bin/phpunit
