name: Testing

on: [ push, pull_request ]

jobs:
  phpcs:
    name: PHP ${{ matrix.php }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: [ '8.0' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Check runtime dependencies
        run: composer check-platform-reqs

      - name: Run Composer Validate
        run: composer validate --strict

      - name: Run Composer Normalize
        run: composer normalize --dry-run

      - name: Run coding style checker
        run: ./vendor/bin/phpcs --standard=WordPress -- *.php
